apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    environment: dev
spec:
  replicas: 15
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:  #podlar oluştuktan sonra değişiklik yaparsak kabul etmez podları silip öyle değişiklik yapmak lazım.Çünkü IgnoredDuringExecution(Execution boyunca değişikliği önemseme)
            nodeSelectorTerms:
            - matchExpressions:
              - key: size
                operator: Exists # NotIn, Exists and DoesNotExist  #durum var ise key=size ve değeri large veya medium  olan
                values:      #operator=NotIn dersen böyle değerleri makinalara kurma
                             #exist dersek value önemli değil key=size olana hepsini kur doesnotexist tam tersi
               