apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    environment: dev
spec:
  replicas: 15
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:   # This field is changed.
          - weight: 10                                        # This field is changed. #Aşağıdaki labellere sahip etiketlere 10 puan ekle çünkü schelur puana göre podlara yerleştiriyor.        
            preference:                                      # This field is changed.   
              matchExpressions:
              - key: size
                operator: In
                values:
                - large
                - medium