apiVersion: v1
kind: Pod  #deployment ile yapmadığın için pod silinirse kubernetes podu yeniden oluşturmaz.deployment ile yapsaydın yeniden kubernetes pod oluştururdu.
metadata:
  name: liveness-tcp
spec:
  containers:
  - name: liveness-tcp
    image: mysql
    ports:
    - containerPort: 3306
    env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
    livenessProbe:
      tcpSocket:
        port: 8080  #normalde bu port açık değil(3306 açık) 15 sn den sonra livenessProbe tcp gönderir ve böyle bi şey yok restart  yapar(podu silmez containerı pull yapıp yeniden çalıştırır)
      initialDelaySeconds: 15
      periodSeconds: 20 (20+15 den sonra yeniden oluşturur.20+15+20 de tekrar bakar)