apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: mongo
    app: todoapp
spec:
  selector:
    app: todoapp
  type: ClusterIP
  ports:
    - name: db
      port: 27017
      targetPort: 27017